void buscarPorTamano(int *numHabitacion, char habitaciones[9][3][40], double precios[9]);
void buscarHotel(int *numHabitacion, char habitaciones[9][3][40], double precios[9]);
void realizarReserva(int numHabitacion, char habitaciones[9][3][40], char clientes[5][2][40], int reservas[10][4]);
void buscarReservaPorCedula(int *numReserva, char clientes[5][2][40], int reservas[10][4]);
void imprimirReserva(int numReserva, int reservas[10][4], char habitaciones[9][3][40], double precios[9]);
void pagarReserva(int numReserva, int reservas[10][4], char habitaciones[9][3][40], double precios[9]);
void leerClientes(char clientes[][2][40], const char *filename);
void leerReservas(int reservas[][4], const char *filename);
void guardarClientes(char clientes[][2][40], const char *filename);
void guardarReservas(int reservas[][4], const char *filename);